# ------------------------------------------------------------------------
#    Localization (custom translations)
# ------------------------------------------------------------------------

translation_dict = {
    "en_US" :
        {
            ("*", "Slam Algorithm") : "Slam Algorithm",
            ("*", "Apply Algorithm to attribute.") : "Apply Algorithm to attribute.",
            ("*", "File Path To Settings") : "File Path To Settings",
            ("*", "Video File Path") : "Video File Path",
            ("*", "Output Folder Path") : "Output Folder Path",
            ("*", "Build Algorithm") : "Build Algorithm",
            ("*", "Import Settings") : "Import Settings",
            ("*", "Export Settings") : "Export Settings",
            ("*", "Apply Settings") : "Apply Settings",
            ("*", "Convert Video To Sequence") : "Convert Video To Sequence",
            ("*", "Processing Video Sequence") : "Processing Video Sequence",
            ("*", "Convert Points To Curve") : "Convert Points To Curve",
            ("*", "Add Virtual Camera") : "Add Virtual Camera",
            ("*", "Create Camera Animation") : "Create Camera Animation",
            ("*", "Curve Builder") : "Curve Builder",
            ("*", "Motion Capture") : "Motion Capture",
            ("*", "Select Algorithm") : "Select Algorithm",
            ("*", "Camera Settings") : "Camera Settings",
            ("*", "Camera frames per second") : "Camera frames per second",
            ("*", "Color order of the images") : "Color order of the images",
            ("*", "Number of features per image") : "Number of features per image",
            ("*", "Scale factor between levels in the scale pyramid") : "Scale factor between levels in the scale pyramid",
            ("*", "Number of levels in the scale pyramid") : "Number of levels in the scale pyramid",
            ("*", "Fast threshold") : "Fast threshold",
            ("*", "Viewer Parameters") : "Viewer Parameters",
        },
    "uk_UA" :
        {
            ("*", "Slam Algorithm") : "Slam Алгоритм",
            ("*", "Apply Algorithm to attribute.") : "Застосувати алгоритм до атрибута.",
            ("*", "File Path To Settings") : "Шлях до файлу налаштування",
            ("*", "Video File Path") : "Шлях до відеофайлу",
            ("*", "Output Folder Path") : "Шлях до папки виводу",
            ("*", "Build Algorithm") : "Зібрати Алгоритм",
            ("*", "Import Settings") : "Імпортувати налаштування",
            ("*", "Export Settings") : "Експортувати налаштування",
            ("*", "Apply Settings") : "Застосувати  налаштування",
            ("*", "Convert Video To Sequence") : "Перетворення відео у послідовність",
            ("*", "Processing Video Sequence") : "Обробка послідовності відео",
            ("*", "Convert Points To Curve") : "Перетворити точки у криву",
            ("*", "Add Virtual Camera") : "Додати віртуальну камеру",
            ("*", "Create Camera Animation") : "Створити анімацію камери",
            ("*", "Curve Builder") : "Будівельник кривої",
            ("*", "Motion Capture") : "Захоплення руху",
            ("*", "Select Algorithm") : "Виберіть Алгоритм",
            ("*", "Camera Settings") : "Налаштування камери",
            ("*", "Camera frames per second") : "Кадри камери у секунду",
            ("*", "Color order of the images") : "Порядок кольорів у зображень",
            ("*", "Number of features per image") : "Кількість точок на одне зображення",
            ("*", "Scale factor between levels in the scale pyramid") : "Коефіцієнт масштабування між рівнями у масштабі піраміди",
            ("*", "Number of levels in the scale pyramid") : "Кількість рівнів у масштабі піраміди",
            ("*", "Fast threshold") : "Швидкий поріг",
            ("*", "Viewer Parameters") : "Параметри перегляду",
        }
}
